server:
  port: 8080
  host:
    url: http://localhost:8080

spring:
  application:
    name: url-shortener
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    url:
    user:
    password:
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: true
    validate-on-migrate: true

springdoc:
  writer-with-default-pretty-printer: true
  show-login-endpoint: true
  pre-loading-enabled: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
    doc-expansion: list
    operations-sorter: method
    syntax-highlight:
      activated: true
      theme: obsidian
    groups-order: asc
  host:
    url: http://localhost:8080