CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (id),
    CONSTRAINT user_username_uq UNIQUE (username),
    CONSTRAINT user_password_size CHECK (length(password) >= 8)
);

CREATE TABLE IF NOT EXISTS url
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    native_link        TEXT         NOT NULL,
    short_link         VARCHAR(255) NOT NULL,
    transactions_count BIGINT,
    user_id            BIGINT,
    created_at         timestamp,
    expired_time       timestamp,
    CONSTRAINT url_pk PRIMARY KEY (id),
    CONSTRAINT url_fk FOREIGN KEY (user_id) REFERENCES users (id)
);