CREATE SEQUENCE IF NOT EXISTS seq_link_id
    START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (id),
    CONSTRAINT user_username_uq UNIQUE (username),
    CONSTRAINT user_password_size CHECK (length(password) >= 8)
);

CREATE TABLE IF NOT EXISTS links
(
    id                 BIGINT DEFAULT nextval('seq_link_id'),
    native_link        TEXT UNIQUE NOT NULL,
    short_link         VARCHAR(255) NOT NULL,
    click_count        BIGINT,
    user_id            BIGINT,
    created_at         timestamp,
    expired_time       timestamp,
    CONSTRAINT url_pk PRIMARY KEY (id),
    CONSTRAINT url_fk FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_short_code ON links(short_link);